services:
  - type: web
    name: recommendation-engine-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: DEBUG
        value: false
      - key: USE_VECTOR_DB
        value: false
      - key: PYTHONUNBUFFERED
        value: 1

  - type: web
    name: recommendation-engine-ui
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    rootDir: ./
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
